### ISSUE TITLE
attach steps in behave html formatter report

### ISSUE THREAD

**Issue by swatantra15081986** [behave-contrib/behave-html-formatter#11]
How can we add steps in the behave html formater report ?

**Comment by modehnal** [comment]
What do you mean add steps in report? The behave steps are already there. Could you attach some use case of what are you trying to achieve?

**Comment by swatantra15081986** [comment]
I want to add some print() data here here

**Comment by modehnal** [comment]
You can use the same embed function from #12, you will have embed function ready.

You just need to change mime type and the data attached:
```
context.embed(mime_type="text/plain",data=your_error_string,caption="PrintData")
```

This will produce a toggle button with name PrintData and upon toggle your data will be there.

**Comment by swatantra15081986** [comment]
Where do I have to paste this code ?

**Comment by modehnal** [comment]
Right, this was meant to be in the same place as with the screenshot.

So in your environment.py file
```
import base64

def before_all(context):
    def embed_data(mime_type, data, caption):
        # If data is empty we want to finish html tag with at least one character
        non_empty_data = " " if not data else data
        for formatter in context._runner.formatters:
            if "html" in formatter.name:
                formatter.embedding(mime_type=mime_type, data=non_empty_data, caption=caption)
                return
    context.embed = embed_data

def before_scenario(context, scenario):
    pass

def after_scenario(context, scenario):
    context.embed(mime_type="text/plain",data=your_error_string,caption="PrintData")
```

**Comment by modehnal** [comment]
@bittner This issue can be closed, it seems I still do not have the rights to it.

**Comment by bittner** [comment]
> it seems I still do not have the rights to it.

Can you elaborate on this? I'm not sure I understand. (Can I do something about it?)
