### ISSUE TITLE
how to add screenshot of fail case in behave html formatters

### ISSUE THREAD

**Issue by swatantra15081986** [behave-contrib/behave-html-formatter#12]
how to add screenshot of fail case in behave html formatters

**Comment by modehnal** [comment]
We have a solution for this in [qecore](https://gitlab.com/dogtail/qecore) tool that is specific for our use cases.

But for a more generic use case you could use something like this:
```
import base64

def before_all(context):
    def embed_data(mime_type, data, caption):
        # If data is empty we want to finish html tag with at least one character
        non_empty_data = " " if not data else data
        for formatter in context._runner.formatters:
            if "html" in formatter.name:
                formatter.embedding(mime_type=mime_type, data=data, caption=caption)
                return
    context.embed = embed_data

def before_scenario(context, scenario):
    pass

def after_scenario(context, scenario):
    image_location = "/tmp/screenshot.png"
    data_base64 = base64.b64encode(open(image_location, "rb").read())
    data = data_base64.decode("utf-8").replace("\n", "")
    context.embed(mime_type="image/png", data=data, caption="Screenshot")
```
The above code - plus your own setup and tests - will at the end produce html page with toggle button Screenshot which will have a screenshot inside.
![test_report](https://user-images.githubusercontent.com/40463522/112306677-598cfc80-8ca0-11eb-8d69-2d2b22845df9.png)

**Comment by modehnal** [comment]
@bittner This issue can be closed, it seems I still do not have the rights to it.

**Comment by bittner** [comment]
> it seems I still do not have the rights to it.

I'm not sure I understand. Are you not allowed to work on this based on your work duties or contract?

If you require any permissions on the repository, let's talk.

**Comment by modehnal** [comment]
@bittner Oh perhaps I am the one that misunderstood, I can work on this but it seems I do not have permission to push to this project and close Issues. I thought you are the one to assign rights to this project.

**Comment by bittner** [comment]
Now you have. Please try again! :factory_worker:

**Comment by malindajudo** [comment]
@modehnal , in your example, 

```python
def after_scenario(context, scenario):
    image_location = "/tmp/screenshot.png"
    data_base64 = base64.b64encode(open(image_location, "rb").read())
    data = data_base64.decode("utf-8").replace("\n", "")
    context.embed(mime_type="image/png", data=data, caption="Screenshot") 
```

How screenshots generated ? Thanks

**Comment by bittner** [comment]
> How screenshots generated ?

You need to use the features of your Web browser integration, e.g. Selenium. See [StackOverflow](https://stackoverflow.com/a/6282203/202834) or [this tutorial](https://pythonspot.com/selenium-take-screenshot/) for explanations.

**Comment by malindajudo** [comment]
> > How screenshots generated ?
> 
> You need to use the features of your Web browser integration, e.g. Selenium. See [StackOverflow](https://stackoverflow.com/a/6282203/202834) or [this tutorial](https://pythonspot.com/selenium-take-screenshot/) for explanations.

Thanks @bittner for the info , now I can generate images, do we need to do anything else? I am using PrettyHTMLFormatter , is that example will be same for PrettyHTMLFormatter ? 

My after scenario is  as follows 
`def after_scenario(context, scenario):
    image_location = "./pytest_results/fail_screenshot.png"
    data_base64 = base64.b64encode(open(image_location, "rb").read())
    data = data_base64.decode("utf-8").replace("\n", "")
    context.embed(mime_type="image/png", data=data, caption="Screenshot")`
    
    And I am getting following error 
`HOOK-ERROR in after_scenario: AttributeError: 'Context' object has no attribute 'formatter'`

Also what I should do when I have multiple png files ? Should I give only the folder location ? 
Thanks

**Comment by malindajudo** [comment]
> > How screenshots generated ?
> 
> You need to use the features of your Web browser integration, e.g. Selenium. See [StackOverflow](https://stackoverflow.com/a/6282203/202834) or [this tutorial](https://pythonspot.com/selenium-take-screenshot/) for explanations.

Thanks @bittner for the info, now I can generate screenshots. However I have multiple screenshots from different scenarios. How I can embedding multiple png files for correct scenario in the report ? I used  PrettyHTMLFormatter and my after_scenario is as follows. Providing the screenshot folder didn't help. Is this something we can not do ? 

`def after_scenario(context, scenario):
    image_location = "./pytest_results/"
    context.embed(mime_type="image/png", data=image_location, caption="Screenshot")`

**Comment by modehnal** [comment]
If you have multiple screenshot you need to do multiple embed calls. Each embed call for each image.

We do not have embedding of content of the entire folder.

The `data=image_location`is for a single file/image data.

**Comment by modehnal** [comment]
Also if you are using  `PrettyHTMLFormatter` and you have issue with the formatter please open a new issue in the correct [project](https://github.com/behave-contrib/behave-html-pretty-formatter). Commenting on closed issues is usually not a way to go.

**Comment by ritheshjarvis** [comment]
Put this below code wherever you want to capture screenshots:

```
screenshot_b64 = context.driver.get_screenshot_as_base64()
for formatter in context._runner.formatters:
    formatter.embedding(mime_type="image/png", data=screenshot_b64, caption="Screenshot")
```

**behave Command:**
`behave --format behave_html_formatter:HTMLFormatter --outfile=reports/report333.html .\features\screenshot.feature`
