### ISSUE TITLE
Gherkin V6 support

### ISSUE THREAD

**Issue by dunossauro** [behave-contrib/behave-html-formatter#21]
When we use HTML formatter, it doesn't report Rule keyword

**Comment by bittner** [comment]
This doesn't seem to be specific to the html-formatter. Can you open this issue on the [behave issue tracker](https://github.com/behave/behave/issues), please?

Thank you for your understanding!

**Comment by bittner** [comment]
Seems like the `Rule` keyword is supported by Behave's development version that you can install from Behave's `master` branch.

See behave/behave#916 for reference.
