### ISSUE TITLE
Add more package owners on PyPI

### ISSUE THREAD

**Issue by bittner** [behave-contrib/behave-html-formatter#3]
The [pyroma](https://pypi.org/project/pyroma/) package gives a few recommendations on healthy package maintenance. One of the rules is to have 3 or more owners of a package (see "Tests" section of their README) to reduce the [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

Hence, @schidlo, if you don't mind, please add some more owners to [behave-html-formatter](https://pypi.org/project/behave-html-formatter/). Suggestions: @jenisys, @bittner (same user names on PyPI)

**Comment by schidlo** [comment]
Hi @bittner , I added you and @jenisys as owners and I will add another one later.

**Comment by bittner** [comment]
Thanks @schidlo, that's awesome! :1st_place_medal:
