### ISSUE TITLE
"Unknown package format" might be an old bug remerging that was #7894

### ISSUE THREAD

**Issue by riesaau** [behave-contrib/behave-html-formatter#37]
On a  mac running Chamilo 1.11.20

When I upload a package from a zip from within chamilo, the first time (and i think maybe the next time too) work okay, but eventually if I keep trying to reupload a package with that same name, I get the above error message. The only way i can still upload my package is by renaming the zip and then importing it again.

**Comment by bittner** [comment]
Chamilo, the LMS? Where do you upload which package to achieve what? Is there any code or terminal command involved? If yes, can paste relevant parts of it?

**Comment by riesaau** [comment]
a scorm package (scorm version 1.2) created in adobe captivate. I am in the learning paths section in chamilo LMS.  I import a SCORM successfully using the icon here,
![image](https://github.com/behave-contrib/behave-html-formatter/assets/97856892/d726cc13-a25e-486e-bf49-c53a78ab744a)
then, in adobe capitvate i may make some changes and make a new zip with the same name as the old scorm and try and reimport it, but after a few times of doing this, chamilo stops me doing it again and gives me the error message I reported above.

**Comment by bittner** [comment]
Are you sure you're in the right place for asking for help on your concern?
