### ISSUE TITLE
Install formatter with Behave (via extras_require)

### ISSUE THREAD

**Issue by bittner** [behave-contrib/behave-html-formatter#5]
If we want to make it easy to include this formatter with a Behave installation we should add it as an [optional dependency](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies) in the Behave project, e.g.

```python
# FILE: setup.py
...
    extras_require={
        'html': ["behave-html-formatter"],
...
```

Install instructions would then look like, e.g.

```console
python3 -m pip install behave[html]
```

## Formatter Auto-Detection

Also, we may want to consider implementing some kind of auto-detection for formatters like ours in Behave, to avoid cumbersome setup instructions and puzzled users.

**Comment by jenisys** [comment]
@bittner
Just provide a pull-request in the `behave` project for "setup.py" (with the changed snippet and the reasoning from here).
